[versions]
agp = "8.13.2"
exoplayer = "2.20.0"
kotlin = "1.9.24"
coreKtx = "1.15.0"
leanback = "1.0.0"
glide = "4.11.0"
media3Exoplayer = "1.5.1"
media3Ui = "1.5.1"
leanbackVersion = "1.2.0"
cardview = "1.0.0"
constraintlayout = "2.2.1"
material = "1.13.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3Ui" }
leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanbackVersion" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

